name: Hello world
on: 
  push:
    branches: 
      - naresh358-patch-1
jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: say hello
        run: echo "Hello World!"
      
    


