name: Print Message Workflow

on:
  push:
    branches:
      - naresh358-patch-1

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print a welcome message
        run: echo "Hello from GitHub Actions!"
